# Generated by Django 3.2.2 on 2021-05-20 19:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Project Name')),
                ('repo_link', models.URLField(blank=True, verbose_name='Repository URL-link')),
                ('change_date', models.DateField(blank=True, verbose_name='Change Date')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='DRAFT', max_length=8, verbose_name='Project Status')),
                ('project_members', models.ManyToManyField(blank=True, related_name='shared_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
