# Generated by Django 3.2.2 on 2021-05-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='change_date',
            field=models.DateTimeField(blank=True, verbose_name='Change Date'),
        ),
    ]
