# Generated by Django 3.2.2 on 2021-05-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210520_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='complete_date',
        ),
        migrations.AddField(
            model_name='todo',
            name='fact_date',
            field=models.DateTimeField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todo',
            name='change_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='create_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
