# Generated by Django 3.2.2 on 2021-05-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20210521_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='fact_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
